language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  email: false
matrix:
    include:
        - os: linux
          python: 3.6
        - os: osx
          python: 3.6.0
